version: '3.3'
services:

  db:
    container_name: foodgram-db
    image: postgres:13.0
    environment:
      POSTGRES_DB: foodgram_db
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    container_name: foodgram-backend
    image: vorchala/foodgram_backend:latest  # Замените YOUR_USERNAME на ваш Docker Hub username
    environment:
      SECRET_KEY: django-insecure-your-secret-key-here-change-in-production
      DEBUG: False  # Для продакшена
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: foodgram_db
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: vorchala/foodgram_frontend:latest  # Замените YOUR_USERNAME на ваш Docker Hub username
    volumes:
      - frontend_build:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_build:
